name: Tree-sitter CLI setup
description: Set up the tree-sitter CLI

inputs:
  tree-sitter-ref:
    description: A tree-sitter commit, tag, or branch
    default: master
  rust-toolchain:
    description: Rust toolchain
    default: stable

runs:
  using: composite
  steps:
    - name: Cache tree-sitter CLI
      uses: actions/cache@v4
      if: inputs.tree-sitter-ref != 'master'
      id: cache-cli
      with:
        path: ${{runner.tool_cache}}/tree-sitter/cli
        key: tree-sitter.cli.${{inputs.tree-sitter-ref}}
    - name: Set up Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1.8
      if: steps.cache-cli.outputs.cache-hit != 'true'
      with:
        toolchain: ${{inputs.rust-toolchain}}
    - name: Install the tree-sitter cli
      if: steps.cache-cli.outputs.cache-hit != 'true'
      shell: bash
      run: |-
        if [[ ${TREE_SITTER_REF:0:1} == v ]]; then
          mkdir -p "$RUNNER_TOOL_CACHE/tree-sitter/cli/bin"
          curl -LSs "$TREE_SITTER_REPO/releases/download/$TREE_SITTER_REF/tree-sitter-linux-x64.gz" | \
            gunzip > "$RUNNER_TOOL_CACHE/tree-sitter/cli/bin/tree-sitter"
          chmod +x "$RUNNER_TOOL_CACHE/tree-sitter/cli/bin/tree-sitter"
        elif [[ $TREE_SITTER_REF =~ ^[[:xdigit:]]{7,40}$ ]]; then
          cargo install --git "$TREE_SITTER_REPO" --ref "$TREE_SITTER_REF" \
            --root "$RUNNER_TOOL_CACHE/tree-sitter/cli" tree-sitter-cli
        else
          cargo install --git "$TREE_SITTER_REPO" --branch "$TREE_SITTER_REF" \
            --root "$RUNNER_TOOL_CACHE/tree-sitter/cli" tree-sitter-cli
        fi
      env:
        TREE_SITTER_REF: ${{inputs.tree-sitter-ref}}
        TREE_SITTER_REPO: https://github.com/tree-sitter/tree-sitter
    - name: Set up the CLI path
      shell: sh
      run: printf '${{runner.tool_cache}}/tree-sitter/cli/bin\n' >> "$GITHUB_PATH"

